# Generated by Django 5.1.4 on 2025-01-01 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_rename_list_id_listings_id_alter_listings_img_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="comment",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="listings", name="num_bid", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listings",
            name="user_bid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_bid",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
