# Generated by Django 5.1.4 on 2025-01-01 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_comments_comment_listings_num_bid_listings_user_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="user_bid",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_bid",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
