# Generated by Django 5.1.4 on 2025-01-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_listings_user_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
