# Generated by Django 5.1.4 on 2025-01-03 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_comments_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="bidders",
            field=models.ManyToManyField(
                blank=True, related_name="bidders_listing", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
